# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simp', '0003_auto_20160107_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='clean_patient_name',
        ),
    ]
